### ISSUE TITLE
OpenSearch checklist

### ISSUE THREAD

**Issue by Earlopain** [zwagoth/e621ng#549]
Code at https://github.com/e621ng/e621ng/tree/switch-to-opensearch

OpenSearch Server
- [x] Compare configration with current Elasticsearch server

e9
- [x] Ensure shard count is still optimal (10-30GB per shard)
- [x] Create prod index, with alias
- [x] Confirm a manual index through rails console works
- [x] Add url param to force search with OS client

e6
- [x] Initial full import to double-check search performance
- [x] Index to both ES and OS simultaneously
- [x] Import all current data again to sync
- [x] Incrementally switch out the default client for OS
- [x] Stop indexing to ES
- [x] Remove ES client
- [ ] Fool NewRelic to instrument OS by aliasing the OS client to the ES client

~~Putting this in an initializer (or even earlier) may make NewRelic pick up OS.~~ NewRelic runs too early, just wait for proper support OS instrumentation. Currently expected jan-mar 2024.
```rb
module Elasticsearch
  VERSION = "7.0.0"

  module Transport
    Client = OpenSearch::Transport::Client
  end
end
```
